"""Shared rollouts schema and passive contracts."""

from .types import (
    ChatCompletion,
    Choice,
    ContentBlock,
    DatasetRow,
    Endpoint,
    Environment,
    EnvironmentConfig,
    EnvironmentFactory,
    EnvironmentResumeMode,
    EvalConfig,
    ImageContent,
    JsonSerializable,
    Logprob,
    Logprobs,
    Message,
    Metric,
    PrepareMessagesFn,
    RowAttempt,
    Score,
    SessionSummary,
    StopReason,
    StreamChunk,
    TextContent,
    ThinkingContent,
    Tool,
    ToolCall,
    ToolCallContent,
    ToolConfirmResult,
    ToolFormatter,
    ToolFunction,
    ToolFunctionParameter,
    ToolRenderConfig,
    ToolResult,
    TrainingSample,
    Trajectory,
    TrajectoryEnvironment,
    TrajectorySession,
    Usage,
)

# charisma: update this compatibility re-export after charisma migrates to DatasetRow.
ProblemRow = DatasetRow
# charisma: update this compatibility re-export after charisma migrates to RowAttempt.
AttemptRow = RowAttempt

__all__ = [
    "ChatCompletion",
    "Choice",
    "ContentBlock",
    "Endpoint",
    "Environment",
    "EnvironmentConfig",
    "EnvironmentFactory",
    "EnvironmentResumeMode",
    "EvalConfig",
    "ImageContent",
    "JsonSerializable",
    "Logprob",
    "Logprobs",
    "Message",
    "Metric",
    "DatasetRow",
    "ProblemRow",
    "PrepareMessagesFn",
    "RowAttempt",
    "AttemptRow",
    "Score",
    "SessionSummary",
    "StopReason",
    "StreamChunk",
    "ToolRenderConfig",
    "TextContent",
    "ThinkingContent",
    "TrainingSample",
    "Tool",
    "ToolCall",
    "ToolCallContent",
    "ToolConfirmResult",
    "ToolFormatter",
    "ToolFunction",
    "ToolFunctionParameter",
    "ToolResult",
    "Trajectory",
    "TrajectoryEnvironment",
    "TrajectorySession",
    "Usage",
]
