"""GLM-4.7-Flash GRPO training with 50% expert pruning on Modal.

Uses pruning recipe to reduce from 64 to 32 experts per layer.
This reduces memory footprint and enables training on 8x H100.

GPU split: 4 for inference (EP=4), 4 for training (EP=4)
- 32 experts / EP=4 = 8 experts per GPU

Run with:
    python -m rollouts.modal_runner --config examples/rl/glm/grpo_glm_pruned_modal.py

First run will:
1. Download GLM-4.7-Flash (~60GB)
2. Apply pruning recipe (64 -> 32 experts)
3. Cache pruned model as Modal snapshot

Subsequent runs use cached pruned model directly.
"""

from examples.rl.glm.base_config import train as _base_train
from rollouts.training.configs import DepsConfig, HardwareConfig
from rollouts.training.grpo import (
    CheckpointConfig,
    GRPOConfig,
    GRPOOutputConfig,
    InferenceConfig,
    ModelConfig,
    RolloutConfig,
    TrainerConfig,
)

# =============================================================================
# Hardware Configuration for Modal
# =============================================================================

GLM_DEPS = DepsConfig(
    python_version="3.12",
    system_packages=(
        "bash",
        "curl",
        "git",
        "build-essential",
        "libnuma1",
        "tmux",
    ),
    pip_packages=(
        # PyTorch with CUDA 12.4
        "torch>=2.4.0",
        "torchvision",
        "torchaudio",
        "flashinfer-python",
        # HF stack
        "hf-transfer",
        "datasets>=4.4.1",
        "accelerate>=0.20.0",
        "peft>=0.7.0",
        # Utils
        "openai",
        "anthropic",
        "dacite",
        "aiohttp",
        "trio",
        "httpx",
        "markdownify",
    ),
    pip_index_url="https://download.pytorch.org/whl/cu124",
    pip_extra_index_url="https://pypi.org/simple",
    bootstrap_commands=(
        "curl -LsSf https://astral.sh/uv/install.sh | sh && . ~/.local/bin/env",
        "~/.local/bin/uv pip install --system 'sglang[all] @ git+https://github.com/sgl-project/sglang.git@main#subdirectory=python'",
        "~/.local/bin/uv pip install --system --upgrade 'transformers>=5.0.0' 'huggingface-hub>=1.4.0'",
        "git clone --depth 1 https://github.com/NVIDIA/Megatron-LM.git /root/Megatron-LM",
    ),
)

hardware = HardwareConfig(
    gpu_type="H100",
    gpu_count=8,
    provider="modal",
    deps=GLM_DEPS,
    use_torchrun=False,  # Megatron handles multi-GPU internally
)

# =============================================================================
# Training Configuration with Pruning
# =============================================================================

MODEL_NAME = "zai-org/GLM-4.7-Flash"

# Pruning recipe: randomly prune 50% of experts (64 -> 32)
# Generated by examples/reap/configs/glm4_flash_prune_50_random.py
PRUNING_RECIPE = "results/reap/glm4_flash_random_50/pruning_recipe.json"

config = GRPOConfig(
    output=GRPOOutputConfig(experiment_name="glm_4.7_flash_pruned_grpo"),
    model=ModelConfig(
        name=MODEL_NAME,
        dtype="bfloat16",
        pruning_recipe=PRUNING_RECIPE,  # Apply 50% expert pruning
    ),
    trainer=TrainerConfig(
        backend="megatron",
        lr=1e-6,
        weight_decay=0.01,
        max_grad_norm=1.0,
        num_minibatches=8,
        loss_type="vanilla",
        # Megatron parallelism: EP=4 on training GPUs
        expert_parallel_size=4,
        tensor_parallel_size=1,
        pipeline_parallel_size=1,
        seq_length=2048,
        # GPU assignment: training on GPUs 4-7 (4 GPUs with EP=4)
        cuda_device_ids=(4, 5, 6, 7),
    ),
    inference=InferenceConfig(
        backend="sglang",
        # Inference on GPUs 0-3 with EP=4
        cuda_device_ids=(0, 1, 2, 3),
        expert_parallel_size=4,
        mem_fraction=0.9,
        startup_timeout=900.0,  # 15 min - first run includes pruning
    ),
    rollout=RolloutConfig(
        batch_size=4,
        n_samples_per_prompt=8,
        temperature=0.7,
        max_seq_len=2048,
        max_tokens=256,
    ),
    checkpoint=CheckpointConfig(
        num_steps=50,
        checkpoint_every=10,
        sync_weights_every=1,
        weight_sync_mode="disk",
    ),
)


def train(config: GRPOConfig | None = None, **kwargs: object) -> dict:
    """Run GLM GRPO training with pruned model."""
    return _base_train(config=config, **kwargs)


if __name__ == "__main__":
    train(config)
